import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
formContext:{
    width:"100%",
    height:"100%",
    bottom:0,
    backgroundColor:"#ffffff",
    alignItems:"center",
    marginTop:30,
    borderTopLeftRadius:30,
    borderTopRightRadius:30
},
form:{
    width:"100%",
    height:"auto",
    padding:10
},
formLabel:{
    color:"black",
    fontSize:18,
    paddingLeft:20,
},
formTextInput:{
   width:"90%",
   borderRadius:50,
   backgroundColor:"#f6f6f6",
   height:40,
   margin:12,
   paddingLeft:10,
},
ButtonCaculator:{
borderRadius:50,
alignItems:"center",
justifyContent:"center",
width:"90%",
backgroundColor:"red",
paddingTop:14,
paddingBottom:14,
marginLeft:12,
marginTop:30,
},
textbuttonCaculator:{
    fontSize:20,
    color:"#ffffff"
},
alertaText:{
    color:"red",
    marginLeft:13,
}
})
export default styles